name: 'GitHub Actions'
'on':
  - push
concurrency: 'ci-${{ github.ref }}'
env:
  APP_IMAGE: looker-api
  DOCKERHUB_USER: '${{ secrets.DOCKERHUB_USER }}'
  DOCKERHUB_TOKEN: '${{ secrets.DOCKERHUB_TOKEN }}'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: [ 7.4, 7.0, 5.6 ]
    steps:
      -
        name: 'Check out the repo'
        uses: actions/checkout@v3
      -
        name: 'Docker login'
        if: env.DOCKERHUB_TOKEN
        run: 'docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"'
      -
        name: 'Build image'
        run: 'docker build --build-arg PHP_VERSION=${{ matrix.php_version }} -t $APP_IMAGE .'
      -
        name: 'Run tests'
        run: 'docker run ${{env.APP_IMAGE}} vendor/bin/phpunit'